name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          wait-on: http://localhost:5173
          start: npx vite --host